mystring='as2 739783asdij1238'
print(len(mystring))
print(mystring.strip())
print(mystring.lower())
print(mystring.upper())
print(mystring.replace("asdi","aadi"))
print(mystring.capitalize())
print(mystring.title())
print(mystring.count("a"))
print(mystring.endswith("6"))
print(mystring.startswith("a"))
print(mystring.find("asdij"))
print(mystring.index("7"))
print(mystring.islower())
print(mystring.isupper())
print(mystring.isalnum())
print(mystring.isalpha())